export const state = {
  tree: null,
  status: null,
  activeFile: null,
  expandedDirs: new Set(),
  changedPaths: new Set(),
  viewerTab: 'changes',
  sidebarTab: 'explorer',
  sidebarWidth: 260,
  viewerWidth: 400,
  projectOpen: false,
  projectRoot: '',
  theme: localStorage.getItem('cc-theme') || 'light',
  viewerFullscreen: false,
  sftpConfigs: [],
  sftpSyncStatus: 'idle',
  sftpConflicts: [],
  inputBoxVisible: localStorage.getItem('cc-input-box') !== '0',
};
